name = "otak-jinro-workers"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "otak-jinro-workers"

[[env.production.durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[env.production.kv_namespaces]]
binding = "PLAYER_DATA"
id = "9e01ad23ddb04f289d0614e8a4a018f8"

[[env.production.kv_namespaces]]
binding = "PUBLIC_ROOMS"
id = "a8b9e985ecf0492383243111fbc7ba88"

[env.staging]
name = "otak-jinro-workers-staging"

# Durable Objects
[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

# Durable Objects Migrations
[[migrations]]
tag = "v1"
new_classes = [ "GameRoom" ]

# KV Namespaces
[[kv_namespaces]]
binding = "PLAYER_DATA"
id = "9e01ad23ddb04f289d0614e8a4a018f8"
preview_id = "d71e2801a36f4359b196277a2990cf96"

[[kv_namespaces]]
binding = "PUBLIC_ROOMS"
id = "a8b9e985ecf0492383243111fbc7ba88"
preview_id = "90027e63b5e643a4a6235cb691546efa"

# Environment Variables
[vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "*"

[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"

# Secrets configuration
# OPENAI_API_KEY is managed via GitHub Actions secrets and wrangler secret commands
# For local development, use: wrangler secret put OPENAI_API_KEY
# For production, secrets are automatically set during CI/CD deployment

# Environment-specific secrets
[env.production.secrets]
# OPENAI_API_KEY is set via GitHub Actions during deployment

[secrets]
# OPENAI_API_KEY is set via wrangler secret put command for local development